
@endpoint = https://98afmpwv0h.execute-api.us-east-1.amazonaws.com/prod

//Create space
POST {{endpoint}}/spaces/
Content-Type: application/json

{
    "location": "Created Location zzz !",
    "name": "Best location !"
}
###

//Get all the spaces
GET {{endpoint}}/spaces
###

//Gell space by id
GET {{endpoint}}/spaces?spaceId=9e28da07-b9fd-4e41-85c6-2efc1182d5f5
###



//Get spaces by location
GET {{endpoint}}/spaces?location=London
###

//Update data based on id
PUT {{endpoint}}/spaces?spaceId=879ed535-d4fb-418c-8e7d-9cabf5ae5f63
Content-Type: application/json

{
    "location": "Updated Location zzz !",
}
###

//Delete space by id
DELETE {{endpoint}}/spaces?spaceId=9e28da07-b9fd-4e41-85c6-2efc1182d5f5
###
